### ISSUE TITLE
Looks like IOS SDK

### ISSUE THREAD

**Issue by tomtharakan** [Paytm-Payments/Paytm_Android_App_Kit#2]
<img width="570" alt="screen shot 2017-04-03 at 10 12 34 pm" src="https://cloud.githubusercontent.com/assets/5616425/24620285/ad80251e-18ba-11e7-8942-e7b3eee34e7c.png">

**Comment by Mohit-Aggarwal1** [comment]
Issue fixed kindly check now, thanks for pointing the issue.
