### ISSUE TITLE
Android sdk have ios sdk file and lib

### ISSUE THREAD

**Issue by macvinod** [Paytm-Payments/Paytm_Android_App_Kit#3]
![screen shot 2017-04-04 at 10 51 21 am](https://cloud.githubusercontent.com/assets/25063214/24642395/b813b350-1924-11e7-9220-3379dcba7d88.png)

Android SDK have iOS SDK files . it is not android SDK please provide me android SDK .

**Comment by Mohit-Aggarwal1** [comment]
Issue fixed kindly check now, thanks for pointing the issue.

**Comment by solankivijay** [comment]
Solanki vijay bahu kanabahi
