### ISSUE TITLE
Class not found : CheckSumServiceHelper for generate Checksum

### ISSUE THREAD

**Issue by devanshi-softvan** [Paytm-Payments/Paytm_Android_App_Kit#35]
Hi sir,
I downloaded jar file for the generate the checksum in my java project. But when I run the code in simple java class it's work perfectly and generate the Checksum. But when I implement it in my project it will generate the Class not fount error in my project.
I download the jar file from the below link : [https://github.com/Paytm-Payments/Paytm_Web_Sample_Kit_Java]

So please provide the correct solution for my issue. 
------------------------
Devanshi Shah

**Comment by devanshi-softvan** [comment]
[](url)

**Comment by d-rahul** [comment]
How you resolved this issue "CheckSumServiceHelper class not found"?
Please comment the solution for the issue before marking issue as closed.
