### ISSUE TITLE
Where is PGSDK_V2.1.jar File in this project

### ISSUE THREAD

**Issue by lovekothari123** [Paytm-Payments/Paytm_Android_App_Kit#41]
In this project PGSDK folder is not found 
without jar file i am not integrate a 
payment gateway 
![without_pgsdk](https://user-images.githubusercontent.com/35691274/40825552-81ff6124-6595-11e8-82a5-5737ecd1b382.png)
In your youtube video show PGSDK folder but their is no PGSDK folder in github 

 
![with_pgsdk_in_youtube](https://user-images.githubusercontent.com/35691274/40825706-19cb86e0-6596-11e8-8344-f5d3d9720fa2.png)
So what we do for that
any one plz help me for that issue

**Comment by Pushpendracolourmoon** [comment]
I am also suffering with the same problem.

**Comment by gagandeep3594** [comment]
i alsooo

**Comment by KeerthiRamesh** [comment]
Hi,

Where I will get the PGSDK .jar file to integrate the paytm .
 please help me with this issue

**Comment by VipinSinghChauhan** [comment]
https://github.com/Sameer-Jani-201/PayTMDemo/tree/master/app/libs
check this link

**Comment by siddeshwer** [comment]
> https://github.com/Sameer-Jani-201/PayTMDemo/tree/master/app/libs
Thanks Bro !!
