### ISSUE TITLE
You are lost in space.

### ISSUE THREAD

**Issue by lovekothari123** [Paytm-Payments/Paytm_Android_App_Kit#42]
After clicking on pay button paytm web
![paytm_error](https://user-images.githubusercontent.com/35691274/40836618-007a6642-65b5-11e8-96d1-9de58b45f989.png)
view show this

**Comment by makzink** [comment]
i am having the same issue.

**Comment by anil-kumar-singh** [comment]
I am getting same problem. Any solution?

**Comment by makzink** [comment]
You have to use the exact same parameters that you used to make the checksum, while you make the call to start payment transaction. The parameters i used are MID, ORDER_ID, CUST_ID, CHANNEL_ID, TXN_AMOUNT, WEBSITE, CALLBACK_URL, INDUSTRY_TYPE_ID. Doing this cleared up my problem. 

Note: The start payment transaction call will have the checksum as an extra parameter that you generated previously.

**Comment by harryharihar** [comment]
paramMap.put("ORDER_ID", paytm.getOrderId());
        paramMap.put("CUST_ID", paytm.getCustId());
        paramMap.put("CHANNEL_ID", paytm.getChannelId());
        paramMap.put("TXN_AMOUNT", paytm.getTxnAmount());
        paramMap.put("WEBSITE", paytm.getWebsite());
        paramMap.put("CALLBACK_URL", paytm.getCallBackUrl());
        paramMap.put("CHECKSUMHASH", data);
        paramMap.put("INDUSTRY_TYPE_ID", paytm.getIndustryTypeId())
        above is my parameters still having the same problem

**Comment by makzink** [comment]
What are the parameters you use to generate checksum hash?

**Comment by harryharihar** [comment]
hashMap.put("ORDER_ID",paytm.getOrderId());
        hashMap.put("CUST_ID",paytm.getCustId());
        hashMap.put("TXN_AMOUNT",paytm.getTxnAmount());
        hashMap.put("CALLBACK_URL",paytm.getCallBackUrl());
        hashMap.put("EMAIL","abc@gmail.com"); 
        hashMap.put("MOBILE","1234567890");
      
       above is my parameters to generate checksum hash from server side
 i will get this type of checksum"qEMe4Y4cB0JU5Uvj9/0FS9QVU+ETvlLQjqyzBjv/EBVPVv7R6QsYtKwR+CzNobdVvVzwhjyLmOy3X5zpXughp4Zqsi899/ZF2pvRrnfUUsI="

**Comment by makzink** [comment]
@harryharihar   The parameters you use to generate checksum and the one you use in paramMap should be the same. Add the missing channel_id, website, industry_id in your hashMap and Add email and mobile in your paramMap.

**Comment by harryharihar** [comment]
below is my parameters to generate checksum 

 "MID": "*******",
  "TXN_AMOUNT": "1",
  "CALLBACK_URL": "https://pguat.paytm.com/paytmchecksum/paytmCallback.jsp",
  "ORDER_ID": "af64047fcbd7437290cf53e12ff89359",
  "WEBSITE": "APP_STAGING",
  "INDUSTRY_TYPE_ID": "Retail",
  "CHANNEL_ID": "WAP",
  "CUST_ID": "8e9a87f49f9f414cb3ef1fd0b0669f40"

below is my paramMap with checksum 
"MID": "********",
  "CALLBACK_URL": "https://pguat.paytm.com/paytmchecksum/paytmCallback.jsp",
  "TXN_AMOUNT": "1",
  "ORDER_ID": "af64047fcbd7437290cf53e12ff89359",
  "WEBSITE": "APP_STAGING",
  "INDUSTRY_TYPE_ID": "Retail",
  "CHECKSUMHASH": "UFPlbUmeKq5wDsRkBRaRd7slqzt8oIN3pVMIihD6JKY6cI6sDCn1TTK6zzQGx3o/BwI/8y3sJZK1i/wpf7McBq3iahKmXEHnB3I+UKIFNRo=",
  "CHANNEL_ID": "WAP",
  "CUST_ID": "8e9a87f49f9f414cb3ef1fd0b0669f40" 

what is going wrong ?

**Comment by aktinfotech** [comment]
paramMap.put("MID", mData.getString("MID"));
        paramMap.put("ORDER_ID", mData.getString("ORDER_ID"));
        paramMap.put("CUST_ID", mData.getString("CUST_ID"));
        paramMap.put("INDUSTRY_TYPE_ID", mData.getString("INDUSTRY_TYPE_ID"));
        paramMap.put("CHANNEL_ID", mData.getString("CHANNEL_ID"));
        paramMap.put("TXN_AMOUNT", mData.getString("TXN_AMOUNT"));
        paramMap.put("WEBSITE", mData.getString("WEBSITE"));
        paramMap.put("CALLBACK_URL", mData.getString("CALLBACK_URL"));
        paramMap.put("CHECKSUMHASH", mData.getString("CHECKSUMHASH"));


I m using this paramMap which i will send to my ap, i vl get a check and will get the same... Please help me with this....

**Comment by ChangdaChen** [comment]
I am getting same problem. The parameters What I use to generate checksum are Mid,Callback_url,Channel_id,Cust_id,Industry_type_id,Order_id,Txn_amount and Website.And I use the method of CheckSumServiceHelper.getCheckSumServiceHelper().genrateCheckSum()  in checksum_2.0.0.jar to get the checksum.Can you help me?

**Comment by ChangdaChen** [comment]
I completed the test in the staging environment. When moving to the formal environment, paytm requires three screenshots of the production environment. I changed my sdk and changed the PG to "PaytmPGService Service = PaytmPGService.getProductionService()". The industry_type_id and website were also modified accordingly. But I still got the error of "You are lost in space". Is that why?
